/**:
    ros__parameters:
      video_device: "/dev/video2"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
      av_device_format: "YUV422P"
      image_width: 320
      image_height: 240
      camera_name: "test_camera"
      camera_info_url: "package://usb_cam/config/camera_info.yaml"
      brightness: 140
      contrast: 200
      saturation: 100
      sharpness: -1
      gain: -1
      auto_white_balance: false
      white_balance: -1
      autoexposure: false
      exposure: -1
      autofocus: false
      focus: -1